import { FridgeItem, Recipe, RescueStats } from './types';

export const initialFridgeItems: FridgeItem[] = [
  {
    id: 'item-1',
    name: 'Baby Spinach',
    category: 'Produce',
    quantity: '250g',
    addedDate: '2026-08-25',
    expiryDate: '2026-08-30',
    daysRemaining: 1,
    status: 'critical',
    iconName: 'Leaf',
    imageUrl: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=500&auto=format&fit=crop&q=80',
    estimatedWasteValue: 80,
    nutritionNotes: 'Rich in iron, vitamin K, and folate',
    recipesCount: 3,
  },
  {
    id: 'item-2',
    name: 'Farm Fresh Eggs',
    category: 'Protein',
    quantity: '6 pcs',
    addedDate: '2026-08-22',
    expiryDate: '2026-08-31',
    daysRemaining: 2,
    status: 'expiring-soon',
    iconName: 'Egg',
    imageUrl: 'https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=500&auto=format&fit=crop&q=80',
    estimatedWasteValue: 60,
    nutritionNotes: '6g protein per egg, choline rich',
    recipesCount: 5,
  },
  {
    id: 'item-3',
    name: 'Greek Yogurt (Organic)',
    category: 'Dairy',
    quantity: '400g',
    addedDate: '2026-08-24',
    expiryDate: '2026-09-01',
    daysRemaining: 3,
    status: 'expiring-soon',
    iconName: 'Milk',
    imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=500&auto=format&fit=crop&q=80',
    estimatedWasteValue: 120,
    nutritionNotes: 'Probiotics and gut-friendly proteins',
    recipesCount: 2,
  },
  {
    id: 'item-4',
    name: 'Roma Vine Tomatoes',
    category: 'Produce',
    quantity: '4 pcs',
    addedDate: '2026-08-26',
    expiryDate: '2026-09-03',
    daysRemaining: 5,
    status: 'fresh',
    iconName: 'Apple',
    imageUrl: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=500&auto=format&fit=crop&q=80',
    estimatedWasteValue: 50,
    nutritionNotes: 'High in lycopene and vitamin C',
    recipesCount: 4,
  },
  {
    id: 'item-5',
    name: 'Fresh Whole Milk',
    category: 'Dairy',
    quantity: '1 Liter',
    addedDate: '2026-08-27',
    expiryDate: '2026-09-02',
    daysRemaining: 4,
    status: 'fresh',
    iconName: 'Milk',
    imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=500&auto=format&fit=crop&q=80',
    estimatedWasteValue: 70,
    nutritionNotes: 'Calcium & Vitamin D fortified',
    recipesCount: 4,
  },
  {
    id: 'item-6',
    name: 'Artisan Sourdough Loaf',
    category: 'Bakery',
    quantity: '1/2 Loaf',
    addedDate: '2026-08-26',
    expiryDate: '2026-08-30',
    daysRemaining: 1,
    status: 'critical',
    iconName: 'Wheat',
    imageUrl: 'https://images.unsplash.com/photo-1589367920969-ab8e050bbb04?w=500&auto=format&fit=crop&q=80',
    estimatedWasteValue: 110,
    nutritionNotes: 'Slow fermented wild yeast sourdough',
    recipesCount: 3,
  },
  {
    id: 'item-7',
    name: 'Paneer (Cottage Cheese)',
    category: 'Dairy',
    quantity: '200g',
    addedDate: '2026-08-27',
    expiryDate: '2026-09-02',
    daysRemaining: 4,
    status: 'fresh',
    iconName: 'Shield',
    imageUrl: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=500&auto=format&fit=crop&q=80',
    estimatedWasteValue: 90,
    nutritionNotes: 'Fresh soft curd cheese, 18g protein',
    recipesCount: 3,
  },
  {
    id: 'item-8',
    name: 'Sweet Bell Peppers',
    category: 'Produce',
    quantity: '2 pcs',
    addedDate: '2026-08-26',
    expiryDate: '2026-09-04',
    daysRemaining: 6,
    status: 'fresh',
    iconName: 'Sparkles',
    imageUrl: 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=500&auto=format&fit=crop&q=80',
    estimatedWasteValue: 40,
    nutritionNotes: 'Antioxidant power, vibrant sweetness',
    recipesCount: 2,
  },
];

export const initialRecipes: Recipe[] = [
  {
    id: 'rec-1',
    title: 'Spinach & Herb Omelette',
    matchScore: 98,
    timeMinutes: 12,
    difficulty: 'Easy',
    servings: 2,
    calories: 280,
    image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=800&auto=format&fit=crop&q=80',
    description:
      'A fluffy, protein-packed omelette folded with sautéed baby spinach, garlic, and fresh ground pepper. Perfect for utilizing expiring leafy greens.',
    tags: ['High Protein', 'Keto Friendly', 'Zero Waste', 'Quick'],
    matchedIngredients: ['Baby Spinach (Expiring tomorrow)', 'Farm Fresh Eggs', 'Butter / Oil'],
    missingIngredients: ['Crumbled Feta (optional)'],
    instructions: [
      'Whisk 3 fresh eggs in a bowl with a pinch of sea salt, freshly cracked black pepper, and 1 tbsp milk.',
      'Heat a teaspoon of olive oil or butter in a non-stick skillet over medium heat.',
      'Add fresh baby spinach and toss until just wilted (around 45 seconds). Remove temporarily.',
      'Pour whisked eggs into the hot pan, tilting to cover the surface evenly.',
      'As the edges set, gently pull them inwards with a spatula so raw egg flows underneath.',
      'Place the wilted spinach across one half, fold the omelette over, and slide onto a warm plate. Garnish with herbs!',
    ],
  },
  {
    id: 'rec-2',
    title: 'Creamy Garlic Spinach Pasta',
    matchScore: 92,
    timeMinutes: 20,
    difficulty: 'Medium',
    servings: 3,
    calories: 450,
    image: 'https://images.unsplash.com/photo-1621996346565-e3d5d6281691?w=800&auto=format&fit=crop&q=80',
    description:
      'Silky fettuccine tossed in a rich garlic cream sauce packed with vibrant wilted spinach and parmesan accents.',
    tags: ['Comfort Food', 'Vegetarian', 'Quick Dinner'],
    matchedIngredients: ['Baby Spinach', 'Fresh Whole Milk', 'Garlic', 'Pasta'],
    missingIngredients: ['Heavy Cream (can sub Milk + Butter)', 'Parmesan Cheese'],
    instructions: [
      'Boil pasta in salted water until al dente; reserve 1/2 cup starchy pasta water.',
      'Melt 2 tbsp butter in a large pan over medium heat, sauté minced garlic until fragrant.',
      'Pour in milk/cream and simmer gently for 3 minutes until thickened.',
      'Toss in washed baby spinach and let it melt into the rich cream.',
      'Add drained pasta and grated cheese, tossing vigorously to coat each ribbon in glossy sauce.',
    ],
  },
  {
    id: 'rec-3',
    title: 'Artisan Sourdough French Toast',
    matchScore: 95,
    timeMinutes: 15,
    difficulty: 'Easy',
    servings: 2,
    calories: 340,
    image: 'https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=800&auto=format&fit=crop&q=80',
    description:
      'Golden, caramelized french toast made from day-old artisan sourdough slices soaked in spiced vanilla egg custard.',
    tags: ['Breakfast', 'Sourdough Rescue', 'Kid Favorite'],
    matchedIngredients: ['Artisan Sourdough Loaf (Expiring)', 'Farm Fresh Eggs', 'Fresh Whole Milk'],
    missingIngredients: ['Maple Syrup', 'Cinnamon Powder'],
    instructions: [
      'In a shallow dish, whisk eggs, milk, cinnamon, and a drop of vanilla extract.',
      'Dip sourdough slices for 20 seconds on each side, allowing bread to absorb the custard.',
      'Melt butter in skillet over medium heat and sear bread for 3-4 minutes per side until golden brown.',
      'Serve warm topped with yogurt or fresh berries.',
    ],
  },
  {
    id: 'rec-4',
    title: 'Royal Palak Paneer',
    matchScore: 88,
    timeMinutes: 30,
    difficulty: 'Medium',
    servings: 4,
    calories: 360,
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800&auto=format&fit=crop&q=80',
    description:
      'A classic North Indian delicacy of tender paneer cubes simmered in a velvety, spiced spinach puree infused with roasted cumin.',
    tags: ['Traditional', 'High Protein', 'Gluten Free'],
    matchedIngredients: ['Baby Spinach', 'Paneer (Cottage Cheese)', 'Roma Vine Tomatoes', 'Whole Milk'],
    missingIngredients: ['Garam Masala', 'Ginger Paste'],
    instructions: [
      'Blanch spinach in boiling water for 2 minutes, then plunge into ice water to preserve vibrant emerald green color.',
      'Blend blanched spinach with green chili and a splash of water into a smooth puree.',
      'Saute cumin seeds, diced onions, ginger, and tomato paste until oil separates.',
      'Stir in spinach puree and simmer for 5 minutes.',
      'Gently fold in fresh paneer cubes and finish with a swirl of fresh cream or butter.',
    ],
  },
];

export const initialRescueStats: RescueStats = {
  foodRescuedKg: 3.4,
  moneySaved: 840,
  ingredientsSaved: 14,
  co2SavedKg: 7.2,
  monthlyGoalKg: 5.0,
};
